### PR TITLE
Remove bot token

### PR DESCRIPTION
**Pull request by Stylite**
You left your bot token in here. I would highly recommend to remove it.

### CODE REVIEW

**Comment by devoxin** [comment]
hi

**Comment by Stylite** [comment]
no

**Comment by devoxin** [comment]
owo what's this

**Comment by henry232323** [comment]
Bah I was hoping nobody would notice until i woke up, lucky it's an empty bot

**Comment by Stylite** [comment]
lmao

**Comment by devoxin** [comment]
lol

**Comment by devoxin** [comment]
Stick it in a properties file and gitignore it

**Comment by Stylite** [comment]
:+1:

**Pull request merged**
